export const INCREASE_CLICKED = "INCREASE_CLICKED";
export const DECREASE_CLICKED = "DECREASE_CLICKED";
export const INCREASE_COUNTER = "INCREASE_COUNTER";
export const DECREASE_COUNTER = "DECREASE_COUNTER";
export const RESET_COUNTER = "RESET_COUNTER";
export const COUNTER_WARNING = "COUNTER_WARNING";